### ISSUE TITLE
Write FooBar test program

### ISSUE THREAD

**Issue by sfadeev** [MakarFadeev/pascal_programs#1]
Write a function called FooBar that takes input integer n and prints all the numbers from 1 upto n in a new line. If the number is divisible by 3 then print "Foo", if the number is divisible by 5 then print "Bar" and if the number is divisible by both 3 and 5, print "FooBar". Otherwise just print the number.

For example FooBar(15) should print as follows:

1
2
Foo
4
Bar
Foo
7
8
Foo
Bar
11
Foo
13
14
FooBar

**Comment by MakarFadeev** [comment]
ok, give me 30 minutes.
